version: '3'
volumes:
  db-data:

services:
  mysql:
    image: mysql:8.0.29
    platform: linux/x86_64
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reversi
      MYSQL_USER: reversi
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
